### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by trainee45**
I will now tap the "Propose changes' button at the bottom of this comment box.
I gather that all lines in green are new additions or proposed changes to the original file?
@GWHodg This text follows the mention 'atGWHodg..so do you get a notification? I don't understand what is happening yet? Doug..or should I say Eyeore?

### CODE REVIEW

**Comment by trainee45** [comment]
The next message I get is:
"This branch has no conflicts with the base branch
Only those with write access to this repository can merge pull requests."
I will now tap Close with Comment.

**Comment by trainee45** [comment]
When I tapped 'Close with Comment' I got this msg:
"Closed with unmerged commits
This pull request is closed, but the trainee45:patch-1 branch has unmerged commits. You can delete this branch if you wish. 
If you wish, you can also delete this fork of GWHodg/hello-world in the settings." I will now tap 'Reopen and comment'

**Comment by trainee45** [comment]
And now I will again tap Close with comment.

**Comment by trainee45** [comment]
I reopened this pull request at 3:00AM NOV6
Does this work?

**Comment by GWHodg** [comment]
Looks like something happened, Doug.
I now have 2 'Pull requests' on my GWHodg account, both titled "
UpdateREADME.md": '#2 opened 6 hours ago by trainee45' and '#1 opened 11
hours ago by trainee45'. When I select & click on #1 there are several
boxes w/ 'trainee45 commented 11 hours ago'.  Will try to forward screen
grabs to you in F/U email.
I also received a couple of invitations from you to 'collaborate'.  I'll
click on 1 & see what happens.
Walt

**Pull request merged**
